services:
  db:
    image: postgres:latest
    container_name: movieflixcontainer
    environment:
      POSTGRES_DB: ${DB_USER}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always